[workspace]
members = [
    "node",
    "pallets/token/*",
    "pallets/exchange/*",
    "pallets/wrap-currency",
    "pallets/nft-market",
    "primitives",
    "runtime/common",
    "runtime/common/chain-extensions",
    "runtime/common/precompiles",
    "runtime/web3games",
]

[profile.release]
panic = "unwind"
