[workspace]
members = [
    "node",
    "pallets/*",
    "primitives",
    "runtime/common",
    "runtime/common/chain-extensions",
    "runtime/common/precompiles",
    "runtime/web3games",
]

[profile.release]
panic = "unwind"
