[workspace]
members = [
	"pallets/token-fungible",
	"pallets/token-multi",
	"pallets/token-non-fungible",
	"primitives",
	"chain-extensions",
	"precompiles",
	"runtime/web3games",
	"node",
]

[profile.release]
panic = "unwind"
