[package]
name = "precompile-utils-macro"
version = "0.1.0"
authors = ["Web3Games Developers"]
edition = "2018"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
sha3 = "0.9.0"
syn = { version = "1.0", features = ["full", "fold", "extra-traits", "visit"] }
