[package]
name = "web3games-exchange-rpc-runtime-api"
version = "0.1.0"
authors = ["Web3Games Developers"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false }
web3games-exchange = { path = "../../../exchange", default-features = false }
web3games-token-fungible = { path = "../../../token-fungible", default-features = false }
primitives = { path = "../../../../primitives", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"web3games-exchange/std",
	"web3games-token-fungible/std",
	"primitives/std",
]
